### ISSUE TITLE
[analysis] Design analysis page

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/delta-ui#136]
## Description

What is basic analysis?

- Select an AOI
- Create time-series chart for specific date range
- Select multiple datasets to compare
- One dataset per chart
- Extract csv or other export of time-series data

Non-basic analysis for the future

- Special visualizations (ex. Sea level change with ranges, fire risk in the coming days/weeks)
- Comparing multiple datasets (with different scales) on one chart 
- Client-side modeling
- 

## Acceptance Criteria

- [ ] Wireframes or prototype showcasing the basic analysis capabilities outlined above that can be reviewed and/or tested by IMPACT stakeholders or users

**Comment by aboydnw** [comment]
@ricardoduplos I added some details here

**Comment by aboydnw** [comment]
thanks for sharing @ricardoduplos ! I put a number of questions on the wireframes in figma comments. Most are probably more related to future development/implementation, but figured I would throw out the questions/thoughts I had.

Do you still want to get some time with NASA folks to review these wireframes? I can think of a few who may be willing to jump on a call.

**Comment by aboydnw** [comment]
@ricardoduplos I showed these to Alexey since it came up a couple times during conversation. Here is the initial feedback he gave:

> This looks good as a first pass for a dynamic visualization. However, I think we need a companion utility to this that replaces the user-selected AOI bbox with a drop-down menu of spatial units (e.g., list of countries; list of states). That’s a slightly more difficult technical challenge because the spatial subset is more complex and will probably require the use of GDAL/OGR-based tools.

Would be happy to coordinate a meeting between you two to discuss further and/or some feedback sessions with other NASA folks
