### ISSUE TITLE
Create dataset `usage` property in delta-ui for linking to code examples

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/delta-ui#188]
Background:
We want some way of including example notebooks + code demonstrating how to use the data. In the future, I think we want to design + implement something like [Landsat's data explorer](https://planetarycomputer.microsoft.com/explore?c=53.8989%2C36.8390&z=10.00&v=2&d=landsat-c2-l1&m=1972+%E2%80%93+1976+%28low+cloud%29&r=Color+infrared&s=false%3A%3A100%3A%3Atrue&ae=0) however for now, I think we just want to add some content to https://www.earthdata.nasa.gov/dashboard/air-quality/datasets/no2/usage that says something like:

>Check out how to use this dataset in this example notebook: [Monthly OMI NO2 time series using STAC API statistics endpoints](https://nasa-impact.github.io/veda-documentation/monthly-omi-no2-timeseries-stac-api.html)

I started looking into adding a dataset property in https://github.com/NASA-IMPACT/delta-ui/tree/ab/add-dataset-usage, however it would be nice to have html content similar to how the main dashboard overview content uses MDX via `MDXModule`

Would it be possible to do something similar for the usage content or perhaps create an interface like `Media`?

For now, I think just the simplest way to add simple html (so we can have both text and a link) would be sufficient and we might make it a more flexible module in the future or redesign the "usage" feature to be more or also like the Planetary Computer's Explorer.

Any advice on how to add the html would be appreciated @danielfdsilva @hanbyul-here @ricardoduplos 

<img width="1699" alt="Screen Shot 2022-06-27 at 7 35 44 AM" src="https://user-images.githubusercontent.com/15016780/175967963-e7fefc6b-e17d-4ac7-8bce-364c6835f2a8.png">

**Comment by aboydnw** [comment]
@abarciauskas-bgse @danielfdsilva @hanbyul-here should this be in the current sprint? from the conversation above it looks like this ticket represents just getting the example notebook content into the dataset usage page. I'll drop it into the current sprint because I know we discussed it as a sprint goal but might have just missed this ticket.

**Comment by abarciauskas-bgse** [comment]
A PR is open to include a reference to the STAC Collection ID: https://github.com/NASA-IMPACT/delta-ui/pull/197

**Comment by abarciauskas-bgse** [comment]
Yes this should be in the current sprint, thanks @aboydnw
