### ISSUE TITLE
Research/wireframe possible time slider or other solution

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/delta-ui#200]
## Description

Similar to COVID dashboard, there is a desire to allow users to quickly slide up and down the timeline while exploring a specific dataset.
Talking to Manil, the primary user need will be to quickly and easily adjust the date to see how the data shifts over time. (Think similar to how you can quickly move to the next day when searching for airport fares) Also sounds like this is fairly familiar functionality for scientists, so he expects they will look for it and quickly comprehend a UI that looks similar to the timeline feature from the COVID dashboard.

![Image](https://user-images.githubusercontent.com/92742765/174912000-a3e76822-204c-421f-baf1-c2523fb8fd23.png)

## Acceptance Criteria

- [ ] Given I am a user exploring a dataset, when I select a layer and date then I can easily move to the adjacent available dates (both forward and backwards) without having to open the calendar component

**Comment by aboydnw** [comment]
@ricardoduplos @danielfdsilva @hanbyul-here I converted this draft issue to an issue in the delta-ui channel

**Comment by ricardoduplos** [comment]
Sharing the wireframes with the proposed design solution. This also includes a revision to the date comparison functionality. 

https://www.figma.com/proto/SA0u0sVdw5vM7g9ulV5Xgw/Wireframes?page-id=1708%3A28082&node-id=1742%3A29319&viewport=-281%2C459%2C0.5&scaling=min-zoom
