### ISSUE TITLE
View Charts on Analysis Page

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/delta-ui#204]
## Description
As a basic scientist
I want to view time-series charts for datasets in my thematic area
So that I can see aggregate values over time and draw insights from them

Part of the Analysis page: https://www.figma.com/file/SA0u0sVdw5vM7g9ulV5Xgw/Wireframes?node-id=1935%3A29389

This ticket is intended to focus just on the viewing of time-series charts. Editing the AOI, date, and dataset selection will be another ticket.
Downloading csv's and directing the user to the respective dataset page will be another ticket.

Can use hardcoded values for AOI and date

## Acceptance Criteria
- [x] Given I am a user of the VEDA Dashboard when I visit the Analysis page under a thematic area then I see time-series charts for all the data in all the datasets in that thematic area

**Comment by aboydnw** [comment]
Dependent on chart component being ready: https://github.com/NASA-IMPACT/delta-ui/issues/233

**Comment by Catalina-Moller** [comment]
#324

**Comment by Catalina-Moller** [comment]
It is possible to see time series charts for all data in all datasets in that subject area!

But we have found 4 issues that need to be fixed for the correct functioning of the charts view.

These are:
-  #324 
-  #325 
-  #326 
- #327
