### ISSUE TITLE
Edit Dates for Analysis Page

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/delta-ui#211]
## Description
As a basic scientist
I want to edit my date selection on the analysis page
So that I can narrow my area of interest to best support the research I am doing or insights I am trying to show to others

Part of the Analysis page: https://www.figma.com/file/SA0u0sVdw5vM7g9ulV5Xgw/Wireframes?node-id=1935%3A29389

This ticket is intended to focus just on editing the date selection. Chart visualization will have taken place on another ticket.
Downloading csv's and directing the user to the respective dataset page will be another ticket.

## Acceptance Criteria
- [ ] Given I have made selections/changes to the dates in the edit sidebar of the Analysis page, when I click Save then the time-series charts reflect those selections
- [ ] Given I have clicked the Edit button on the Analysis page, when I click Cancel then I am returned to the Analysis main page and my changes are lost
- [ ] Given I have previously made a selection of dates on the Analysis page, when I click Edit to open the sidebar then those selections are represented as current selections in the sidebar

**Comment by j08lue** [comment]
In the current Netlify deployment https://veda-ui.netlify.app/covid-19/analysis I found this issue:

Refining the date range does not seem to work - date range does not get changed in the plot and no new data is loaded.

### Steps to reproduce:
2. Go to Analysis
3. Select AOI and date range (e.g. 01/01/2020 - 01/11/2022)
4. Select NO2
5. Click Save
6. See timeseries
7. Click Refine
8. Change date range (by date picker or typing, e.g. change starting date to 01/01/2005)
9. Click Save
10. Expected: See timeseries with updated date range
11. Actual: Same date range as before refinement

You can see the issue in the below screenshot: When you add a second dataset during refinement, the new one is loaded with the refined date/AOI but the old one stays the same.

![Image](https://user-images.githubusercontent.com/3404817/199963399-b82cb32c-552e-4392-a259-6626b8ea69e7.png)

Same for AOI refinement, actually - I see the same plot as before. I would expect a new data extraction and the values to change when I change the AOI. (edited)

**Comment by Catalina-Moller** [comment]
The behavior of the date when saving, editing or canceling changes on the analysis page works as expected. 

We found two possible improvements to be made to this functionality:
- #332 
- #333
