### ISSUE TITLE
Polar projection

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/delta-ui#219]
## Description

Based on feedback from EIS Freshwater when reviewing alternative projections.

> The snow people like to work in polar projection.

Note from Hanbyul in Slack:

> Oh I quickly looked up mapbox gl doc and it seems we can offer polar projection by tweaking the parameters of lambertConformalConic projection, (https://docs.mapbox.com/mapbox-gl-js/guides/projections/) maybe we can pre-bake these parameters and offer polar projection

## Acceptance Criteria
1. A user viewing the dataset explorer page can choose to view the dataset in a polar projection

**Comment by danielfdsilva** [comment]
Link for `lambertConformalConic` with parameters to emulate a polar projection: https://www.earthdata.nasa.gov/dashboard/eis/datasets/tws-anomaly/explore?datetime=2002-12-01T00%3A00%3A00.000Z&position=19.5853%7C69.572%7C2.99&projection=lambertConformalConic%7C-40%2C0%7C90%2C90
