### ISSUE TITLE
Synthesize feedback from design review meetings

### ISSUE THREAD

**Issue by ricardoduplos** [NASA-IMPACT/delta-ui#230]
Capture feedback from stakeholders, concerning:

1. Analysis page wireframes
2. Date widget wireframes
3. Alternative projections UI implementation

Document in progress: https://docs.google.com/document/d/1tkz2cUM7yH49mqJI9U26CRprAcngrFh3SbRQHR2mxg4/edit

**Comment by aboydnw** [comment]
@ricardoduplos should this be in the current sprint? 
Also FYI stakeholders at NASA were asking about this, so a finished document would definitely be useful for communicating our findings to a broader audience!

**Comment by danielfdsilva** [comment]
Design review report: https://docs.google.com/document/d/1hgbaHXW9YLXfeO5W__r77Cr-rln0kkUlX66ZkdzHesU/edit#heading=h.6adwhfqtcjlt
