### ISSUE TITLE
Chart features for Analysis page

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/delta-ui#233]
- zoom / brush 
- sync multiple charts (like: https://bl.ocks.org/ColinEberhardt/raw/3c780088c363d1515403f50a87a87121/ ) 

- toggle on/off stat 
- download as csv
- export chart as png

**Comment by aboydnw** [comment]
Duplicate of https://github.com/NASA-IMPACT/delta-ui/issues/227
