### ISSUE TITLE
Test dashboard with upgraded API

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/delta-ui#245]
# Description
Now that we've upgraded the backend to a new version, we're planning to switch our current staging API URLs with the new ones.

Before doing this though, we need to make sure everything with the dashboard works as is, i.e. all the datasets are showing up, all the dates are there, etc.

This ticket involves doing manual testing for the dashboard deployed with the new APIs.

The test dashboard url is https://deploy-preview-107--visex.netlify.app/
The current staging dashboard url is https://www.earthdata.nasa.gov/dashboard/

# Acceptance Criteria
- [x] All the datasets that exist in the current staging dashboard exist in the test dashboard
- [x] The cogs for all the datasets shows up in the map in the test dashboard
- [x] The available dates (in the date widget) for each dataset are the same as the current dashboard
- [x] Spot checking of cog visualization for random dates in the test dashboard

**Comment by Catalina-Moller** [comment]
Attached is the document with the Notes - Test dashboard with upgraded API
[Notes - Test dashboard with upgraded API.pdf](https://github.com/NASA-IMPACT/delta-ui/files/9608608/Notes.-.Test.dashboard.with.upgraded.API.pdf)
