### ISSUE TITLE
Get user feedback for chart behaviour

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/delta-ui#286]
@danielfdsilva We can use this ticket to collect items that need feedback.
- tooltip 'sync' behavior
- number/unit

**Comment by aboydnw** [comment]
@hanbyul-here I believe this is complete, right? Or do you all need additional input after the meeting with EIS earlier this week?

**Comment by danielfdsilva** [comment]
@aboydnw We got feedback on these points. closing
