### ISSUE TITLE
Recommendation: In the Dataset "Nighttime Lights" show the points on the map in a closer view. 

### ISSUE THREAD

**Issue by Catalina-Moller** [NASA-IMPACT/delta-ui#303]
### **Description:** 
When a user enters in the "Nighttime Lights" Dataset's explorer view on one of the points that has a layer and then moves away the points are not visible again until they are very far away, it is recommended that the points are visible earlier in order to be able to enter a point that has a layer more easily. 
It also happens that when zooming in on the map the dots disappear at a very far distance. 

**Evidence:** [Video ](https://www.screencast.com/t/Nr64EteJj)

**Comment by nerik** [comment]
@hanbyul-here @danielfdsilva Thoughts on this? just fix by setting a higher min zoom on the frontmatter?
What's happening is that beyond markers zoom level, raster layers at lowish zoom levels take a very long time to load. I'd say maybe show the spinner again when switching from markers to raster?

**Comment by Catalina-Moller** [comment]
With this change, the user experience is much better. Thank you!
