### ISSUE TITLE
Determine how to visualize cryospheric data (data in polar projections)

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/delta-ui#38]
Summarizing from an email chain on this topic we have been working with ICESat-2 Sea Ice Thickness data, see https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/issues/63 in 2-d web mercator and it doesn't seem to suffice as-is so this ticket is to explore other options.

Things we are pursuing:
- [ ] Checking with ESA colleagues on their process
- [ ] Looking at alternative mapbox projections per https://delta-projections.surge.sh/
- [ ] Looking at 3D options but this is still a WIP for Mapbox

**Comment by aboydnw** [comment]
@abarciauskas-bgse this may end up being resolved by #199 
I'm going to block this for now until we 1) have #199 merged and 2) configure ICESat-2 dataset and can test/validate this issue

**Comment by aboydnw** [comment]
closing in favor of https://github.com/NASA-IMPACT/delta-ui/issues/219
